{{- if .Values.networkPolicy.create }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "k8status.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8status.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "k8status.selectorLabels" . | nindent 6 }}
  ingress: []
  egress:
    - to:
      ports:
      - protocol: TCP
        port: 53
      - protocol: UDP
        port: 53
  policyTypes:
    - Ingress
    - Egress
{{- end }}
