apiVersion: rbac.authorization.k8s.io/v1
{{ if .Values.k8status.allNamespaces }}
kind: ClusterRole
{{ else }}
kind: Role
{{ end }}
metadata:
  name: {{ include "k8status.fullname" . }}
  labels:
    {{- include "k8status.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  - pods
  {{ if .Values.k8status.allNamespaces }}
  - namespaces
  {{ end }}
  verbs:
  - list
