version: '3.4'

services:
  ui:
    build:
      context: .
      target: build-ui
    environment:
      - PROXY_OVERWRITE=http://server:8080
    entrypoint: ""
    command: sh -c 'npm install && npm start'
    depends_on:
      - server
    volumes:
      - ./ui:/workspace/ui
    ports:
      - 3000:3000
  server:
    build:
      context: .
      target: build-server
    command: sh -c 'go install github.com/cosmtrek/air@latest && air --build.args_bin="--namespace argocd"'
    volumes:
      - ~/.kube:/root/.kube
    ports:
      - 8080:8080
